### ISSUE TITLE
Keeps The Connection Alive After Closing The Play Scene

### ISSUE THREAD

**Issue by DinShub** [Rocher0724/socket.io-unity#10]
Hey,
I have this issue where the socket is still connecting to the server even after I close the play scene.
Every minute it keeps connecting.

**Comment by gdebojyoti** [comment]
@DinShub  Are you disconnecting the socket in the Destroy method?

```
private void OnDestroy () {
    socket.Disconnect ();
}
```

**Comment by DinShub** [comment]
I did, but I'm not using this package anymore. It did continue to send messages even though I disconnected, but its not relevant for me anymore, so I'm closing this thread.
